# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"global_path": "00_core.ipynb",
         "chaogate": "00_core.ipynb",
         "tup2ar": "00_core.ipynb",
         "chaogate.Vin_tup": "00_core.ipynb",
         "chaogate.Vin_ar": "00_core.ipynb",
         "chaogate.Vin_slice": "00_core.ipynb",
         "sweep": "00_core.ipynb",
         "iterate_map": "00_core.ipynb",
         "iterate": "00_core.ipynb",
         "lyapunov": "00_core.ipynb",
         "grid": "00_core.ipynb",
         "bifurcate": "00_core.ipynb",
         "booleanize_ar": "00_core.ipynb",
         "booleanize": "00_core.ipynb",
         "boolean_gradient": "00_core.ipynb",
         "boolean_divergence": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Noeloikeau.github.io/chaogate/"

git_url = "https://github.com/Noeloikeau/chaogate/tree/master/"

def custom_doc_links(name): return None
